import 'package:drift/drift.dart';
import 'package:flexify/database/database.dart';

const defaultExercises = [
  ('Arnold press', 'Shoulders'),
  ('Back extension', 'Back'),
  ('Barbell bench press', 'Chest'),
  ('Barbell biceps curl', 'Arms'),
  ('Barbell bent-over row', 'Back'),
  ('Barbell shoulder press', 'Shoulders'),
  ('Barbell shrug', 'Shoulders'),
  ('Cable fly', 'Chest'),
  ('Cable lateral raise', 'Shoulders'),
  ('Cable pull-down', 'Back'),
  ('Chest fly', 'Chest'),
  ('Chin-up', 'Back'),
  ('Close-grip pull-up', 'Back'),
  ('Crunch', 'Core'),
  ('Deadlift', 'Back'),
  ('Decline bench press', 'Chest'),
  ('Diamond push-up', 'Chest'),
  ('Dumbbell bench press', 'Chest'),
  ('Dumbbell biceps curl', 'Arms'),
  ('Dumbbell bent-over row', 'Back'),
  ('Dumbbell fly', 'Chest'),
  ('Dumbbell lateral raise', 'Shoulders'),
  ('Dumbbell shoulder press', 'Shoulders'),
  ('Dumbbell shrug', 'Shoulders'),
  ('Good morning', 'Back'),
  ('Hanging leg raise', 'Core'),
  ('Hyperextension', 'Back'),
  ('Incline bench press', 'Chest'),
  ('Lat pull-down', 'Back'),
  ('Leg curl', 'Legs'),
  ('Leg extension', 'Legs'),
  ('Leg press', 'Legs'),
  ('Leg raise', 'Core'),
  ('Lunge', 'Legs'),
  ('Narrow-grip push-up', 'Chest'),
  ('Neck curl', 'Shoulders'),
  ('Overhead triceps extension', 'Arms'),
  ('Preacher curl', 'Arms'),
  ('Pull-down', 'Back'),
  ('Pull-up', 'Back'),
  ('Push-up', 'Chest'),
  ('Reverse grip pull-down', 'Back'),
  ('Reverse grip pushdown', 'Arms'),
  ('Roman chair leg raise', 'Core'),
  ('Romanian deadlift', 'Back'),
  ('Russian twist', 'Core'),
  ('Seated calf raise', 'Calves'),
  ('Shoulder shrug', 'Shoulders'),
  ('Squat', 'Legs'),
  ('Standing calf raise', 'Calves'),
  ('T-bar row', 'Back'),
  ('Triceps dip', 'Arms'),
  ('Triceps extension', 'Arms'),
  ('Triceps pushdown', 'Arms'),
  ('Upright row', 'Shoulders'),
  ('Weighted Russian twist', 'Core'),
  ('Wide-grip pull-up', 'Back'),
  ('Wide-grip push-up', 'Chest'),
  ('Standard Push-Ups', 'Upper Body'),
  ('Wide Grip Push-Ups', 'Upper Body'),
  ('Close Grip Push-Ups', 'Upper Body'),
  ('Diamond Push-Ups', 'Upper Body'),
  ('Pike Push-Ups', 'Upper Body'),
  ('Decline Push-Ups', 'Upper Body'),
  ('Incline Push-Ups', 'Upper Body'),
  ('Spiderman Push-Ups', 'Upper Body'),
  ('Archer Push-Ups', 'Upper Body'),
  ('Hindu Push-Ups', 'Upper Body'),
  ('Divebomber Push-Ups', 'Upper Body'),
  ('Pseudo Planche Push-Ups', 'Upper Body'),
  ('Clapping Push-Ups', 'Upper Body'),
  ('One-Arm Push-Ups', 'Upper Body'),
  ('Knee Push-Ups', 'Upper Body'),
  ('Wall Push-Ups', 'Upper Body'),
  ('Uneven Push-Ups', 'Upper Body'),
  ('Cross-Arm Push-Ups', 'Upper Body'),
  ('Sphinx Push-Ups', 'Upper Body'),
  ('Tricep Push-Ups', 'Upper Body'),
  ('Sphinx to Plank', 'Upper Body'),
  ('Side-to-Side Push-Ups', 'Upper Body'),
  ('Clock Push-Ups', 'Upper Body'),
  ('Aztec Push-Ups', 'Upper Body'),
  ('Flying Squirrel Push-Ups', 'Upper Body'),
  ('Maltese Push-Ups', 'Upper Body'),
  ('Fingertip Push-Ups', 'Upper Body'),
  ('Knuckle Push-Ups', 'Upper Body'),
  ('Staggered Push-Ups', 'Upper Body'),
  ('Typewriter Push-Ups', 'Upper Body'),
  ('Scorpion Push-Ups', 'Upper Body'),
  ('Superman Push-Ups', 'Upper Body'),
  ('Isometric Push-Up Hold', 'Upper Body'),
  ('Plank Up-Downs (Commandos)', 'Upper Body'),
  ('Shoulder Taps', 'Upper Body'),
  ('Tricep Dips', 'Upper Body'),
  ('Bench Dips', 'Upper Body'),
  ('180 Jump Dips', 'Upper Body'),
  ('Handstand Push-Ups', 'Upper Body'),
  ('Handstand Hold', 'Upper Body'),
  ('Wall Walks', 'Upper Body'),
  ('Pull-Ups', 'Upper Body'),
  ('Chin-Ups', 'Upper Body'),
  ('Wide Grip Pull-Ups', 'Upper Body'),
  ('Commando Pull-Ups', 'Upper Body'),
  ('Muscle-Ups', 'Upper Body'),
  ('Inverted Rows', 'Upper Body'),
  ('Active Bar Hang', 'Upper Body'),
  ('Negative Pull-Ups', 'Upper Body'),
  ('Scapular Pull-Ups', 'Upper Body'),
  ('Front Lever Raises', 'Upper Body'),
  ('Front Lever Hold', 'Upper Body'),
  ('Back Lever Hold', 'Upper Body'),
  ('Arm Circles', 'Upper Body'),
  ('Reverse Snow Angels', 'Upper Body'),
  ('Superman Holds', 'Upper Body'),
  ('Superman Pulses', 'Upper Body'),
  ('Swimmer', 'Upper Body'),
  ('Bodyweight Reverse Fly', 'Upper Body'),
  ('Bodyweight Squats', 'Lower Body'),
  ('Pistol Squats', 'Lower Body'),
  ('Assisted Pistol Squats', 'Lower Body'),
  ('Jump Squats', 'Lower Body'),
  ('Sissy Squats', 'Lower Body'),
  ('Bulgarian Split Squats', 'Lower Body'),
  ('Cossack Squats', 'Lower Body'),
  ('Shrimp Squats', 'Lower Body'),
  ('Sumo Squats', 'Lower Body'),
  ('1 1/4 Squats', 'Lower Body'),
  ('Deep Squat Hold', 'Lower Body'),
  ('Wall Sit', 'Lower Body'),
  ('Squat Pulses', 'Lower Body'),
  ('Prisoner Squats', 'Lower Body'),
  ('Squat Jacks', 'Lower Body'),
  ('Surrender Squats', 'Lower Body'),
  ('Plie Squats', 'Lower Body'),
  ('Frog Squats', 'Lower Body'),
  ('Heel-Elevated Squats', 'Lower Body'),
  ('Toe-Elevated Squats', 'Lower Body'),
  ('Squat to Calf Raise', 'Lower Body'),
  ('Squat to Alternating Knee Crunch', 'Lower Body'),
  ('Chair Pose Hold', 'Lower Body'),
  ('Forward Lunges', 'Lower Body'),
  ('Reverse Lunges', 'Lower Body'),
  ('Walking Lunges', 'Lower Body'),
  ('Jump Lunges', 'Lower Body'),
  ('Curtsy Lunges', 'Lower Body'),
  ('Side Lunges', 'Lower Body'),
  ('Lunge Pulses', 'Lower Body'),
  ('Pendulum Lunges', 'Lower Body'),
  ('Lunge to Knee Drive', 'Lower Body'),
  ('Lunge with Twist', 'Lower Body'),
  ('Around-the-Clock Lunges', 'Lower Body'),
  ('Sprinter Lunges', 'Lower Body'),
  ('Deficit Lunges', 'Lower Body'),
  ('Glute Bridges', 'Lower Body'),
  ('Single-Leg Glute Bridges', 'Lower Body'),
  ('Hip Thrusts (Bodyweight)', 'Lower Body'),
  ('Glute Bridge Hold', 'Lower Body'),
  ('Glute Bridge Walkouts', 'Lower Body'),
  ('Single-Leg Glute Bridge Pulses', 'Lower Body'),
  ('Frog Pumps', 'Lower Body'),
  ('Calf Raises', 'Lower Body'),
  ('Single-Leg Calf Raises', 'Lower Body'),
  ('Donkey Kicks', 'Lower Body'),
  ('Fire Hydrants', 'Lower Body'),
  ('Hydrant Extensions', 'Lower Body'),
  ('Step-Ups', 'Lower Body'),
  ('Good Mornings (Bodyweight)', 'Lower Body'),
  ('Single-Leg Deadlift (RDL)', 'Lower Body'),
  ('Hamstring Curls (Sliding)', 'Lower Body'),
  ('Abductor Slides', 'Lower Body'),
  ('Clamshells', 'Lower Body'),
  ('Reverse Clamshells', 'Lower Body'),
  ('Leg Circles (Side Lying)', 'Lower Body'),
  ('Inner Thigh Lifts', 'Lower Body'),
  ('Straight Leg Kickbacks', 'Lower Body'),
  ('Kneeling Squats', 'Lower Body'),
  ('Forearm Plank', 'Core'),
  ('High Plank', 'Core'),
  ('Side Plank', 'Core'),
  ('Reverse Plank', 'Core'),
  ('Side Plank Dips', 'Core'),
  ('Side Plank with Leg Lift', 'Core'),
  ('Plank with Arm Reach', 'Core'),
  ('Plank with Leg Lift', 'Core'),
  ('Plank to Down Dog', 'Core'),
  ('Bear Plank', 'Core'),
  ('Bear Crawl Hold', 'Core'),
  ('Bear Crawl Shoulder Taps', 'Core'),
  ('Thread the Needle (Side Plank)', 'Core'),
  ('Plank Saws', 'Core'),
  ('Plank Drag', 'Core'),
  ('Hollow Body Hold', 'Core'),
  ('Hollow Body Rocks', 'Core'),
  ('L-Sit', 'Core'),
  ('V-Ups', 'Core'),
  ('Bicycle Crunches', 'Core'),
  ('Russian Twists', 'Core'),
  ('Flutter Kicks', 'Core'),
  ('Scissor Kicks', 'Core'),
  ('Dead Bugs', 'Core'),
  ('Bird-Dog', 'Core'),
  ('Sit-Ups', 'Core'),
  ('Straight-Leg Sit-Up', 'Core'),
  ('Crunches', 'Core'),
  ('Reverse Crunches', 'Core'),
  ('Butterfly Crunches', 'Core'),
  ('Heel Touches (Penguins)', 'Core'),
  ('Toe Touches', 'Core'),
  ('Leg Raises', 'Core'),
  ('Hanging Leg Raises', 'Core'),
  ('Hanging Knee Tucks', 'Core'),
  ('Knees to Elbows', 'Core'),
  ('Toes to Bar', 'Core'),
  ('Dragon Flags', 'Core'),
  ('Windshield Wipers', 'Core'),
  ('Starfish Crunches', 'Core'),
  ('Ab Rollouts (Sliders)', 'Core'),
  ('Ab Pulses', 'Core'),
  ('90/90 Crunch', 'Core'),
  ('Tabletop Crunch', 'Core'),
  ('Cross-Body Mountain Climbers', 'Core'),
  ('Slow Mountain Climbers', 'Core'),
  ('Tuck Crunches', 'Core'),
  ('Suitcase Crunches', 'Core'),
  ('Boat Pose Hold', 'Core'),
  ('Sprinter Crunches', 'Core'),
  ('Banana Roll', 'Core'),
  ('Alternating Jackknives', 'Core'),
  ('Burpees', 'Full Body & Cardio'),
  ('Burpees with Pull-Up', 'Full Body & Cardio'),
  ('Mountain Climbers', 'Full Body & Cardio'),
  ('3-Way Mountain Climber', 'Full Body & Cardio'),
  ('Jumping Jacks', 'Full Body & Cardio'),
  ('Star Jacks', 'Full Body & Cardio'),
  ('Walking Jacks', 'Full Body & Cardio'),
  ('Bear Crawls', 'Full Body & Cardio'),
  ('Crab Walk', 'Full Body & Cardio'),
  ('Crocodile Crawl', 'Full Body & Cardio'),
  ('Inchworms', 'Full Body & Cardio'),
  ('Inchworm to Push-Up', 'Full Body & Cardio'),
  ('Gorilla Walks', 'Full Body & Cardio'),
  ('Duck Walks', 'Full Body & Cardio'),
  ('Spider Crawl', 'Full Body & Cardio'),
  ('High Knees', 'Full Body & Cardio'),
  ('Butt Kicks', 'Full Body & Cardio'),
  ('Jumping Knee Tucks', 'Full Body & Cardio'),
  ('4-Count Bodybuilders', 'Full Body & Cardio'),
  ('Plank to Bear Squat', 'Full Body & Cardio'),
  ('Sprawls', 'Full Body & Cardio'),
  ('Surfer Jumps', 'Full Body & Cardio'),
  ('Squat Thrusts', 'Full Body & Cardio'),
  ('Broad Jump to Backpedal', 'Full Body & Cardio'),
  ('Suicides', 'Full Body & Cardio'),
  ('1-2-3 Side-Steps', 'Full Body & Cardio'),
  ('Plank Jacks', 'Full Body & Cardio'),
  ('Squat Jumps with 180 Turn', 'Full Body & Cardio'),
  ('Split Jumps', 'Full Body & Cardio'),
  ('Line Jumps', 'Full Body & Cardio'),
  ('Pogo Hops', 'Full Body & Cardio'),
  ('Lateral Skaters', 'Full Body & Cardio'),
  ('Heismans', 'Full Body & Cardio'),
  ('Agility Dots', 'Full Body & Cardio'),
  ('X-Jumps', 'Full Body & Cardio'),
  ('Burpee Broad Jumps', 'Full Body & Cardio'),
  ('Half Burpees', 'Full Body & Cardio'),
  ('Ski Jumps', 'Full Body & Cardio'),
  ('Seal Jacks', 'Full Body & Cardio'),
  ('Cross Jacks', 'Full Body & Cardio'),
  ('Box Jumps', 'Full Body & Cardio'),
  ('Broad Jumps', 'Full Body & Cardio'),
  ('Tuck Jumps', 'Full Body & Cardio'),
  ('Frog Jumps', 'Full Body & Cardio'),
  ('Lateral Bounds', 'Full Body & Cardio'),
  ('Ape Reach', 'Animal Flow / Mobility'),
  ('Beast Reach', 'Animal Flow / Mobility'),
  ('Crab Reach', 'Animal Flow / Mobility'),
  ('Underswitch', 'Animal Flow / Mobility'),
  ('Side Kickthrough', 'Animal Flow / Mobility'),
  ('Front Kickthrough', 'Animal Flow / Mobility'),
  ('Scorpion Reach', 'Animal Flow / Mobility'),
  ('Loaded Beast', 'Animal Flow / Mobility'),
  ('Jumping Loaded Beast', 'Animal Flow / Mobility'),
  ('Bunny Hops', 'Animal Flow / Mobility'),
  ('Ostrich Walk', 'Animal Flow / Mobility'),
  ('Alligator Crawl', 'Animal Flow / Mobility'),
  ('Lizard Crawl', 'Animal Flow / Mobility'),
  ('Skin the Cat', 'Gymnastics / Calisthenics'),
  ('Straddle Planche', 'Gymnastics / Calisthenics'),
  ('Tuck Planche', 'Gymnastics / Calisthenics'),
  ('Advanced Tuck Planche', 'Gymnastics / Calisthenics'),
  ('Human Flag', 'Gymnastics / Calisthenics'),
  ('Human Flag (Tuck)', 'Gymnastics / Calisthenics'),
  ('One Arm Pull-Up (Negative)', 'Gymnastics / Calisthenics'),
  ('Clapping Pull-Ups', 'Gymnastics / Calisthenics'),
  ('L-Sit Pull-Ups', 'Gymnastics / Calisthenics'),
  ('Handstand Pirouettes', 'Gymnastics / Calisthenics'),
  ('Cat-Cow Stretch', 'Mobility'),
  ('Downward Dog', 'Mobility'),
  ('Upward Dog', 'Mobility'),
  ("Child's Pose", 'Mobility'),
  ('Cobra Pose', 'Mobility'),
  ('Pigeon Pose', 'Mobility'),
  ('Thread the Needle Stretch', 'Mobility'),
  ('90/90 Hip Stretch', 'Mobility'),
  ("World's Greatest Stretch", 'Mobility'),
  ('Deep Lunge Stretch', 'Mobility'),
  ('Quad Stretch (Standing)', 'Mobility'),
  ('Hamstring Stretch (Seated)', 'Mobility'),
  ('Butterfly Stretch', 'Mobility'),
  ('Iron Cross Stretch', 'Mobility'),
  ('Scorpion Stretch', 'Mobility'),
  ('Thoracic Extensions', 'Mobility'),
  ('Neck Circles', 'Mobility'),
  ('Wrist Rotations', 'Mobility'),
  ('Wrist Extension Stretch', 'Mobility'),
  ('Thumb Stretch', 'Mobility'),
  ('Flat Fist Stretch', 'Mobility'),
  ('Prayer Stretch', 'Mobility'),
  ('Ankle Circles', 'Mobility'),
  ('Hip Circles', 'Mobility'),
  ('Torso Twists', 'Mobility'),
  ('Arm Crossovers', 'Mobility'),
  ('Leg Swings (Forward/Back)', 'Mobility'),
  ('Leg Swings (Side/Side)', 'Mobility'),
  ('Standing Toe Touches', 'Mobility'),
  ('Forward Fold', 'Mobility'),
  ('Groin Stretch', 'Mobility'),
  ('Kneeling Hip Flexor Stretch', 'Mobility'),
  ('Couch Stretch', 'Mobility'),
  ('Calf Stretch (Wall)', 'Mobility'),
  ('Wall Slides', 'Mobility'),
  ('Scapular Wall Slides', 'Mobility'),
  ('Finger Taps', 'Hand Dexterity'),
  ('Tabletop Finger Lifts', 'Hand Dexterity'),
  ('Finger Spreads', 'Hand Dexterity'),
  ('Wrist Flexion & Extension', 'Hand Dexterity'),
];

const defaultPlans = [
  PlansCompanion(id: Value(1), days: Value('Monday')),
  PlansCompanion(id: Value(2), days: Value('Wednesday')),
  PlansCompanion(id: Value(3), days: Value('Friday')),
];

final defaultPlanExercises = [
  ...['Barbell bench press', 'Squat', 'Lat pull-down', 'Leg press'].map(
    (e) => PlanExercisesCompanion.insert(planId: 1, exercise: e, enabled: true),
  ),
  ...[
    'Deadlift',
    'Overhead triceps extension',
    'Dumbbell biceps curl',
    'Barbell bent-over row',
  ].map(
    (e) => PlanExercisesCompanion.insert(planId: 2, exercise: e, enabled: true),
  ),
  ...['Leg press', 'Pull-up', 'Push-up', 'Crunch'].map(
    (e) => PlanExercisesCompanion.insert(planId: 3, exercise: e, enabled: true),
  ),
];

final defaultSets = defaultExercises.map(
  (exercise) => GymSetsCompanion(
    created: Value(DateTime.now().toLocal()),
    name: Value(exercise.$1),
    reps: const Value(0),
    weight: const Value(0),
    hidden: const Value(true),
    unit: const Value('kg'),
    category: Value(exercise.$2),
  ),
);
