org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:ActiveProcessorCount=8 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=6
android.useAndroidX=true
android.nonTransitiveRClass=false
android.nonFinalResIds=true
android.builtInKotlin=false
android.newDsl=false
