const weekdays = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

const exercises = [
  'Squat',
  'Leg press',
  'Lunge',
  'Deadlift',
  'Leg extension',
  'Leg curl',
  'Standing calf raise',
  'Seated calf raise',
  'Bench press',
  'Chest fly',
  'Push-up',
  'Pull-down',
  'Pull-up',
  'Bent-over row',
  'Upright row',
  'Shoulder press',
  'Lateral raise',
  'Shoulder shrug',
  'Pushdown',
  'Triceps extension',
  'Biceps curl',
  'Crunch',
  'Russian twist',
  'Leg raise',
  'Back extension',
  'Dips'
];
