const weekdays = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

const exercises = [
  'Arnold press',
  'Back extension',
  'Barbell bench press',
  'Barbell biceps curl',
  'Barbell bent-over row',
  'Barbell shoulder press',
  'Barbell shrug',
  'Bench press',
  'Bent-over row',
  'Biceps curl',
  'Cable fly',
  'Cable lateral raise',
  'Cable pull-down',
  'Chest fly',
  'Chin-up',
  'Close-grip pull-up',
  'Crunch',
  'Deadlift',
  'Decline bench press',
  'Diamond push-up',
  'Dips',
  'Dumbbell bench press',
  'Dumbbell biceps curl',
  'Dumbbell bent-over row',
  'Dumbbell fly',
  'Dumbbell lateral raise',
  'Dumbbell shoulder press',
  'Dumbbell shrug',
  'Good morning',
  'Hanging leg raise',
  'Hyperextension',
  'Incline bench press',
  'Lat pull-down',
  'Lateral raise',
  'Leg curl',
  'Leg extension',
  'Leg press',
  'Leg raise',
  'Lunge',
  'Narrow-grip push-up',
  'Overhead triceps extension',
  'Preacher curl',
  'Pull-down',
  'Pull-up',
  'Push-up',
  'Reverse grip pull-down',
  'Reverse grip pushdown',
  'Roman chair leg raise',
  'Romanian deadlift',
  'Russian twist',
  'Seated calf raise',
  'Shoulder press',
  'Shoulder shrug',
  'Squat',
  'Standing calf raise',
  'T-bar row',
  'Triceps dips',
  'Triceps extension',
  'Triceps pushdown',
  'Upright row',
  'Weighted Russian twist',
  'Wide-grip pull-up',
  'Wide-grip push-up'
];
