name: macos

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Enable macOS desktop support
        run: flutter config --enable-macos-desktop

      - name: Check if running on macOS
        id: check_os
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]] || [[ "$(uname)" == "Darwin" ]]; then
            echo "is_macos=true" >> $GITHUB_OUTPUT
          else
            echo "is_macos=false" >> $GITHUB_OUTPUT
            echo "Warning: Not running on macOS, skipping macOS build"
          fi

      - name: Build MacOS
        if: steps.check_os.outputs.is_macos == 'true'
        run: flutter build macos --release

      - name: Archive Release files
        if: steps.check_os.outputs.is_macos == 'true'
        run: |
          cd build/macos/Build/Products/Release
          zip -r MacOS.zip .

      - name: Upload zip
        if: steps.check_os.outputs.is_macos == 'true'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/macos/Build/Products/Release/MacOS.zip
          asset_name: MacOS zip
          tag: ${{ github.ref }}
          overwrite: false

      - name: Skip build (not macOS)
        if: steps.check_os.outputs.is_macos == 'false'
        run: |
          echo "Skipping macOS build because this is not running on macOS"
          echo "This is expected when testing with 'act' on non-macOS systems"
